In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [73]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [74]:
# define a function to get the value
def v_function_3d(x, y, z):
    return 3 * x + 4 * y - z

In [122]:
# the np.linspace() function returns the interval between the given numbers.
x = np.linspace(0, 4, 5)
y = np.linspace(0, 5, 6)
z = np.linspace(0, 6, 7)

# in three dimensions, a point's coordinates are treated collectively as a single object.
points = (x, y, z)

# meshgrid, it changes NumPy arrays into coordinate matrices or grids of values
X, Y, Z = np.meshgrid(*points, indexing="ij")

In [151]:
# get the values
values = v_function_3d(X, Y, Z)

## Use SciPy’s interpn() Method for 3D Interpolation in Python

In [110]:
from scipy.interpolate import interpn

In [111]:
# coordinates to sample the gridded data are
point = np.array([2.21, 3.12, 1.15])

# evaluate the 3d interpolating function at a point
method = 'linear'    # or 'nearest', 'linear', 'cubic', ...
print(interpn(points, values, point, method=method))

[17.96]


## Use RegularGridInterpolator for 3D Interpolation in Python

In [83]:
from scipy.interpolate import RegularGridInterpolator as RGI

In [84]:
# make the interpolator
rgi = RGI(points, values=values)

In [87]:
pnt = (2.21, 3.12, 1.15)

print(rgi(pnt).round(2))

17.96


## Save to file

In [157]:
data = np.vstack([X.ravel(), Y.ravel(), Z.ravel(), values.ravel()]).T

print(data)

[[ 0.  0.  0.  0.]
 [ 0.  0.  1. -1.]
 [ 0.  0.  2. -2.]
 [ 0.  0.  3. -3.]
 [ 0.  0.  4. -4.]
 [ 0.  0.  5. -5.]
 [ 0.  0.  6. -6.]
 [ 0.  1.  0.  4.]
 [ 0.  1.  1.  3.]
 [ 0.  1.  2.  2.]
 [ 0.  1.  3.  1.]
 [ 0.  1.  4.  0.]
 [ 0.  1.  5. -1.]
 [ 0.  1.  6. -2.]
 [ 0.  2.  0.  8.]
 [ 0.  2.  1.  7.]
 [ 0.  2.  2.  6.]
 [ 0.  2.  3.  5.]
 [ 0.  2.  4.  4.]
 [ 0.  2.  5.  3.]
 [ 0.  2.  6.  2.]
 [ 0.  3.  0. 12.]
 [ 0.  3.  1. 11.]
 [ 0.  3.  2. 10.]
 [ 0.  3.  3.  9.]
 [ 0.  3.  4.  8.]
 [ 0.  3.  5.  7.]
 [ 0.  3.  6.  6.]
 [ 0.  4.  0. 16.]
 [ 0.  4.  1. 15.]
 [ 0.  4.  2. 14.]
 [ 0.  4.  3. 13.]
 [ 0.  4.  4. 12.]
 [ 0.  4.  5. 11.]
 [ 0.  4.  6. 10.]
 [ 0.  5.  0. 20.]
 [ 0.  5.  1. 19.]
 [ 0.  5.  2. 18.]
 [ 0.  5.  3. 17.]
 [ 0.  5.  4. 16.]
 [ 0.  5.  5. 15.]
 [ 0.  5.  6. 14.]
 [ 1.  0.  0.  3.]
 [ 1.  0.  1.  2.]
 [ 1.  0.  2.  1.]
 [ 1.  0.  3.  0.]
 [ 1.  0.  4. -1.]
 [ 1.  0.  5. -2.]
 [ 1.  0.  6. -3.]
 [ 1.  1.  0.  7.]
 [ 1.  1.  1.  6.]
 [ 1.  1.  2.  5.]
 [ 1.  1.  3

In [162]:
filename = 'data.csv'

delimiter = '\t'
header = delimiter.join(['x','y','z','value'])

np.savetxt(filename, data, fmt='%.3f', delimiter=delimiter, header=header, comments='')

## Read from file with Pandas

In [163]:
df = pd.read_csv(filename, delimiter=delimiter)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x       210 non-null    float64
 1   y       210 non-null    float64
 2   z       210 non-null    float64
 3   value   210 non-null    float64
dtypes: float64(4)
memory usage: 6.7 KB


In [165]:
data = df.values
print(data)

[[ 0.  0.  0.  0.]
 [ 0.  0.  1. -1.]
 [ 0.  0.  2. -2.]
 [ 0.  0.  3. -3.]
 [ 0.  0.  4. -4.]
 [ 0.  0.  5. -5.]
 [ 0.  0.  6. -6.]
 [ 0.  1.  0.  4.]
 [ 0.  1.  1.  3.]
 [ 0.  1.  2.  2.]
 [ 0.  1.  3.  1.]
 [ 0.  1.  4.  0.]
 [ 0.  1.  5. -1.]
 [ 0.  1.  6. -2.]
 [ 0.  2.  0.  8.]
 [ 0.  2.  1.  7.]
 [ 0.  2.  2.  6.]
 [ 0.  2.  3.  5.]
 [ 0.  2.  4.  4.]
 [ 0.  2.  5.  3.]
 [ 0.  2.  6.  2.]
 [ 0.  3.  0. 12.]
 [ 0.  3.  1. 11.]
 [ 0.  3.  2. 10.]
 [ 0.  3.  3.  9.]
 [ 0.  3.  4.  8.]
 [ 0.  3.  5.  7.]
 [ 0.  3.  6.  6.]
 [ 0.  4.  0. 16.]
 [ 0.  4.  1. 15.]
 [ 0.  4.  2. 14.]
 [ 0.  4.  3. 13.]
 [ 0.  4.  4. 12.]
 [ 0.  4.  5. 11.]
 [ 0.  4.  6. 10.]
 [ 0.  5.  0. 20.]
 [ 0.  5.  1. 19.]
 [ 0.  5.  2. 18.]
 [ 0.  5.  3. 17.]
 [ 0.  5.  4. 16.]
 [ 0.  5.  5. 15.]
 [ 0.  5.  6. 14.]
 [ 1.  0.  0.  3.]
 [ 1.  0.  1.  2.]
 [ 1.  0.  2.  1.]
 [ 1.  0.  3.  0.]
 [ 1.  0.  4. -1.]
 [ 1.  0.  5. -2.]
 [ 1.  0.  6. -3.]
 [ 1.  1.  0.  7.]
 [ 1.  1.  1.  6.]
 [ 1.  1.  2.  5.]
 [ 1.  1.  3

## griddata

In [160]:
from scipy.interpolate import griddata

In [175]:
point = np.array([2.21, 3.12, 1.15])

griddata(data[:, :3], data[:, 3], point, method=method)

array([17.96])

## Convert back to a tuple of meshgrid point coordinates

In [168]:
x = np.unique(data[:, 0])
y = np.unique(data[:, 1])
z = np.unique(data[:, 2])

points = (x, y, z)
        
values = data[:, 3].reshape(5, 6, 7)

In [176]:
# coordinates to sample the gridded data are
point = np.array([2.21, 3.12, 1.15])

# evaluate the 3d interpolating function at a point
method = 'linear'    # or 'nearest', 'linear', 'cubic', ...
print(interpn(points, values, point, method=method))

[17.96]
