In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# This is an example

In [1]:
print('Hello Jupyter!')

Hello Jupyter!


In [2]:
a = 987
b = 8907
print(a + b)

9894


## Showing numpy

Numpy is a package for numeric processing

In [2]:
x = np.linspace(0, 10, 101)

In [3]:
x

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [4]:
x * 10

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

In [5]:
y = np.sin(x)/(x + 1)

In [6]:
y

array([ 0.        ,  0.09075765,  0.16555778,  0.22732324,  0.27815596,
        0.31961703,  0.35290155,  0.37895158,  0.39853116,  0.41227732,
        0.42073549,  0.42438446,  0.42365413,  0.41893834,  0.41060405,
        0.39899799,  0.38445139,  0.36728326,  0.34780273,  0.32631038,
        0.30309914,  0.27845463,  0.25265513,  0.22597128,  0.19866564,
        0.17099204,  0.14319483,  0.11550808,  0.08815478,  0.06134598,
        0.03528   ,  0.01014162, -0.01389861, -0.03668505, -0.05807752,
       -0.07795183, -0.0962001 , -0.11273109, -0.12747039, -0.14036044,
       -0.1513605 , -0.16044649, -0.16761073, -0.1728615 , -0.17622261,
       -0.17773275, -0.17744482, -0.17542513, -0.17175252, -0.16651739,
       -0.15982071, -0.1517729 , -0.14249269, -0.13210594, -0.12074445,
       -0.10854467, -0.09564646, -0.08219187, -0.06832385, -0.05418502,
       -0.0399165 , -0.02565669, -0.01154019,  0.00230327,  0.01574989,
        0.02868267,  0.04099228,  0.05257791,  0.06334787,  0.07

In [9]:
plt.axhline(0, color='black', linewidth=3)
plt.plot(x, y, 'seagreen')
plt.grid()
plt.show()

In [10]:
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(19680801)

fig, ax = plt.subplots()
for color in ['tab:blue', 'tab:orange', 'tab:green']:
    n = 750
    x, y = np.random.rand(2, n)
    scale = 200.0 * np.random.rand(n)
    ax.scatter(x, y, c=color, s=scale, label=color,
               alpha=0.3, edgecolors='none')

ax.legend()
ax.grid(True)

plt.show()

In [14]:
a = np.linspace(10, 20, 18)
a

array([10.        , 10.58823529, 11.17647059, 11.76470588, 12.35294118,
       12.94117647, 13.52941176, 14.11764706, 14.70588235, 15.29411765,
       15.88235294, 16.47058824, 17.05882353, 17.64705882, 18.23529412,
       18.82352941, 19.41176471, 20.        ])

In [15]:
a.shape

(18,)

In [18]:
m = a.reshape(3, 6).round(2)
m

array([[10.  , 10.59, 11.18, 11.76, 12.35, 12.94],
       [13.53, 14.12, 14.71, 15.29, 15.88, 16.47],
       [17.06, 17.65, 18.24, 18.82, 19.41, 20.  ]])

In [19]:
m.shape

(3, 6)

In [20]:
m.transpose()

array([[10.  , 13.53, 17.06],
       [10.59, 14.12, 17.65],
       [11.18, 14.71, 18.24],
       [11.76, 15.29, 18.82],
       [12.35, 15.88, 19.41],
       [12.94, 16.47, 20.  ]])

### Pandas

In [27]:
filename = 'ca-500.csv'
df = pd.read_csv(filename, sep=';', dtype='string')
df

first_name      last_name                    company_name  \
0    Francoise  Rautenstrauch               Riebesell, H F Jr   
1       Kendra           Loud               Deloitte & Touche   
2      Lourdes       Bauswell               Oklahoma Neon Inc   
3       Hannah        Edmison              M B A Paint Stores   
4          Tom          Loeza       Sheraton Shreveport Hotel   
..         ...            ...                             ...   
495       Erin      Delbosque             Curtiss Wright Corp   
496  Kassandra       Marushia        Phelps Tool & Die Co Inc   
497     Leslee        Matsuno         Factory Mattress Outlet   
498     Daniel         Dobler  Cosgroves N End Plbg & Hdwr Co   
499    Antonio          Unruh      Mission Lincoln Properties   

                    address            city province   postal        phone1  \
0        2335 Canton Hwy #6         Windsor       ON  N8N 3N2  519-569-8399   
1           6 Arch St #9757          Alcida       NB  E8J 2C4  506-363-1526   
2       9547 Belmont Rd #21      Belleville       ON  K8P 1B3  613-903-7043   
3    73 Pittsford Victor Rd       Vancouver       BC  V5Z 3K2  604-334-3686   
4      447 Commercial St Se     LIle-Perrot       QC  J7V 4T4  514-487-6096   
..                      ...             ...      ...      ...           ...   
495   357 W Mount Royal Ave       Longueuil       QC  J4M 2A8  450-316-7813   
496    123 Euclid Ave #9396         Nanaimo       BC  V9R 1C9  250-646-6446   
497     1251 E Main St #990          Quebec       QC  G1H 1A6  418-460-5773   
498       259 W 17th St #39       Beresford       NB  E8K 1B7  506-617-2607   
499              9 Route 38  Port Coquitlam       BC  V3C 2Z4  604-624-7690   

           phone2                                      email  \
0    519-978-6179  francoise.rautenstrauch@rautenstrauch.com   
1    506-932-4472                            kloud@gmail.com   
2    613-638-6682                   lourdes_bauswell@aol.com   
3    604-692-7694                           hannah@yahoo.com   
4    514-727-4760                        tom.loeza@gmail.com   
..            ...                                        ...   
495  450-491-8703                               erin@cox.net   
496  250-571-5058                        kassandra@gmail.com   
497  418-543-9015                 leslee_matsuno@matsuno.org   
498  506-951-8403                         ddobler@dobler.com   
499  604-966-9833                  antonio.unruh@hotmail.com   

                                         web  
0               http://www.riebesellhfjr.com  
1              http://www.deloittetouche.com  
2             http://www.oklahomaneoninc.com  
3              http://www.mbapaintstores.com  
4     http://www.sheratonshreveporthotel.com  
..                                       ...  
495         http://www.curtisswrightcorp.com  
496        http://www.phelpstooldiecoinc.com  
497     http://www.factorymattressoutlet.com  
498   http://www.cosgrovesnendplbghdwrco.com  
499  http://www.missionlincolnproperties.com  

[500 rows x 11 columns]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   first_name    500 non-null    string
 1   last_name     500 non-null    string
 2   company_name  500 non-null    string
 3   address       500 non-null    string
 4   city          500 non-null    string
 5   province      500 non-null    string
 6   postal        500 non-null    string
 7   phone1        500 non-null    string
 8   phone2        500 non-null    string
 9   email         500 non-null    string
 10  web           500 non-null    string
dtypes: string(11)
memory usage: 43.1 KB


In [30]:
df['name'] = df['first_name'] + ' ' + df['last_name']

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   first_name    500 non-null    string
 1   last_name     500 non-null    string
 2   company_name  500 non-null    string
 3   address       500 non-null    string
 4   city          500 non-null    string
 5   province      500 non-null    string
 6   postal        500 non-null    string
 7   phone1        500 non-null    string
 8   phone2        500 non-null    string
 9   email         500 non-null    string
 10  web           500 non-null    string
 11  name          500 non-null    string
dtypes: string(12)
memory usage: 47.0 KB


In [32]:
df

first_name      last_name                    company_name  \
0    Francoise  Rautenstrauch               Riebesell, H F Jr   
1       Kendra           Loud               Deloitte & Touche   
2      Lourdes       Bauswell               Oklahoma Neon Inc   
3       Hannah        Edmison              M B A Paint Stores   
4          Tom          Loeza       Sheraton Shreveport Hotel   
..         ...            ...                             ...   
495       Erin      Delbosque             Curtiss Wright Corp   
496  Kassandra       Marushia        Phelps Tool & Die Co Inc   
497     Leslee        Matsuno         Factory Mattress Outlet   
498     Daniel         Dobler  Cosgroves N End Plbg & Hdwr Co   
499    Antonio          Unruh      Mission Lincoln Properties   

                    address            city province   postal        phone1  \
0        2335 Canton Hwy #6         Windsor       ON  N8N 3N2  519-569-8399   
1           6 Arch St #9757          Alcida       NB  E8J 2C4  506-363-1526   
2       9547 Belmont Rd #21      Belleville       ON  K8P 1B3  613-903-7043   
3    73 Pittsford Victor Rd       Vancouver       BC  V5Z 3K2  604-334-3686   
4      447 Commercial St Se     LIle-Perrot       QC  J7V 4T4  514-487-6096   
..                      ...             ...      ...      ...           ...   
495   357 W Mount Royal Ave       Longueuil       QC  J4M 2A8  450-316-7813   
496    123 Euclid Ave #9396         Nanaimo       BC  V9R 1C9  250-646-6446   
497     1251 E Main St #990          Quebec       QC  G1H 1A6  418-460-5773   
498       259 W 17th St #39       Beresford       NB  E8K 1B7  506-617-2607   
499              9 Route 38  Port Coquitlam       BC  V3C 2Z4  604-624-7690   

           phone2                                      email  \
0    519-978-6179  francoise.rautenstrauch@rautenstrauch.com   
1    506-932-4472                            kloud@gmail.com   
2    613-638-6682                   lourdes_bauswell@aol.com   
3    604-692-7694                           hannah@yahoo.com   
4    514-727-4760                        tom.loeza@gmail.com   
..            ...                                        ...   
495  450-491-8703                               erin@cox.net   
496  250-571-5058                        kassandra@gmail.com   
497  418-543-9015                 leslee_matsuno@matsuno.org   
498  506-951-8403                         ddobler@dobler.com   
499  604-966-9833                  antonio.unruh@hotmail.com   

                                         web                     name  
0               http://www.riebesellhfjr.com  Francoise Rautenstrauch  
1              http://www.deloittetouche.com              Kendra Loud  
2             http://www.oklahomaneoninc.com         Lourdes Bauswell  
3              http://www.mbapaintstores.com           Hannah Edmison  
4     http://www.sheratonshreveporthotel.com                Tom Loeza  
..                                       ...                      ...  
495         http://www.curtisswrightcorp.com           Erin Delbosque  
496        http://www.phelpstooldiecoinc.com       Kassandra Marushia  
497     http://www.factorymattressoutlet.com           Leslee Matsuno  
498   http://www.cosgrovesnendplbghdwrco.com            Daniel Dobler  
499  http://www.missionlincolnproperties.com            Antonio Unruh  

[500 rows x 12 columns]

In [37]:
df_selected = df.loc[df['city'] == 'Montreal', ['first_name', 'last_name', 'city', 'email']]
df_selected

first_name   last_name      city                     email
67      Mammie      Cisney  Montreal            mammie@cox.net
109      Tesha       Brang  Montreal             tesha@aol.com
233     Harris       Sheck  Montreal            harris@cox.net
236     Maddie      Foulds  Montreal        maddie@hotmail.com
239  Steffanie      Meinen  Montreal  steffanie.meinen@cox.net
315        Val      Bigaud  Montreal        val_bigaud@aol.com
350      Denny      Zeanah  Montreal   denny_zeanah@zeanah.com
411      Luann      Michon  Montreal             luann@cox.net
422     Verona       Jobst  Montreal    verona_jobst@jobst.org
424      Rikki    Montalgo  Montreal        rikki@montalgo.com
468      Ricki       Traux  Montreal     ricki.traux@traux.com
483  Clemencia  Momplaisir  Montreal     cmomplaisir@yahoo.com

In [38]:
df_selected.sort_values('last_name')

first_name   last_name      city                     email
315        Val      Bigaud  Montreal        val_bigaud@aol.com
109      Tesha       Brang  Montreal             tesha@aol.com
67      Mammie      Cisney  Montreal            mammie@cox.net
236     Maddie      Foulds  Montreal        maddie@hotmail.com
422     Verona       Jobst  Montreal    verona_jobst@jobst.org
239  Steffanie      Meinen  Montreal  steffanie.meinen@cox.net
411      Luann      Michon  Montreal             luann@cox.net
483  Clemencia  Momplaisir  Montreal     cmomplaisir@yahoo.com
424      Rikki    Montalgo  Montreal        rikki@montalgo.com
233     Harris       Sheck  Montreal            harris@cox.net
468      Ricki       Traux  Montreal     ricki.traux@traux.com
350      Denny      Zeanah  Montreal   denny_zeanah@zeanah.com

In [39]:
df['province'].value_counts()

province
ON    175
QC    116
BC     72
AB     42
NB     30
NS     23
SK     21
MB     12
NL      8
PE      1
Name: count, dtype: Int64

In [41]:
df['province'].value_counts().plot(kind='barh')

<Axes: ylabel='province'>